### ISSUE TITLE
Docker trouble when using Graviton2

### ISSUE THREAD

**Issue by robd003** [ottertune/ot-agent#56]
Getting this error when trying to start the agent docker container on AWS Graviton2:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/sh: exec format error
```

This is for the image specified in the dashboard: public.ecr.aws/ottertune/agent:0.3.7

**Comment by YuzeLiao** [comment]
Hey @robd003,

Please try to add `--platform linux/amd64` to your docker run command. Feel free to let us know if you have any other questions!
