### ISSUE TITLE
Multiple Vulnerabilities

### ISSUE THREAD

**Issue by laurentdelosieresfactorial** [ottertune/ot-agent#97]
Hello,

Multiple vulnerabilities have been detected in the Docker image of OtterTune Agent of severity Critical and High. Would it be possible to update the folllowing packages to their latest versions or remove them if not used ?

- dpkg
- libtasn-1.6
- glibc
- pcre2
- openssl
- wheel
- gnutls28
- werkzeug
- krb5
- ipython
- mysql-connector-python
- xz-utils
- gzip

Thank you in advance,

Best,
L.

**Comment by ruogudu** [comment]
Hi L.

Thanks for the suggestion! We have updated our dependencies.

Ruogu
